export {default as NavBar} from './NavBar'
export {default as Hero} from './Hero'
export {default as Projects} from './Projects'
export {default as Skills} from './Skills'
export {default as Education} from './Education'